# Generated by Django 3.2.25 on 2024-09-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='threat',
            table=None,
        ),
    ]
