# Generated by Django 3.2.25 on 2024-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatapp', '0002_alter_threat_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='origin_country_alpha2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='origin_country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
